### ISSUE TITLE
Closed bracket ')' is  missing in readme file examples 1,2,3 and 4

### ISSUE THREAD

**Issue by chanduthedev** [Gi60s/timeout-queue#1]
HI @Gi60s,

Thanks for the nice tool. I observed there is some error in the example code. closed bracket is missing in the example 1,2,3 and 4 while initializing the queue. Please correct it. 

Before:
-------

`const queue = timeoutQueue(500, function(value) {
    console.log('Expired ' + value);
};`

After:
-----

`const queue = timeoutQueue(500, function(value) {
    console.log('Expired ' + value);
});`

**Comment by Gi60s** [comment]
LOL. Thanks for the catch. I've updated those examples

I'm glad you like the library.
