### ISSUE TITLE
npm install throwing 'ENOENT: no such file or directory'

### ISSUE THREAD

**Issue by chanduthedev** [Gi60s/timeout-queue#2]
Hi @Gi60s ,

When I run **npm install timeout-queue** I am getting below error. But When I run **yarn add timeout-queue** its working fine. 

$ npm install timeout-queue
npm ERR! path node_modules/timeout-queue/timeout-queue.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'node_modules/timeout-queue/timeout-queue.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2019-06-13T03_42_58_413Z-debug.log

**Node version:** v8.12.0
**Operating System:** OSX 10.14.5 

Thanks in advance.

**Comment by Gi60s** [comment]
Thanks for the bug report. I've applied a fix and published it as version `1.0.2`.
